### ISSUE TITLE
Замечания по Solve4

### ISSUE THREAD

**Issue by eligantRU** [kloun1592/oop-labs#6]
- [x] Строки принято закрывать, смотри за концами файлов. Включи отображение пробельных символов, квадратик(EOF) должен быть на последней строке(в которой нет кода)

- [x] "Разработать на основе данной функции программу, запрашивающую со стандартного потока ввода коэффициенты уравнения 4 степени и вычисление при помощи функции Solve4 корней данного уравнения с последующим выводом результата в стандартный поток вывода." - не реализовано

- [x] *.h файлы созданы для объявлений, а не для сокрытия реализации. Вынеси реализацию функций в *.cpp файл(ы) (6_lab_4.h)

- [x] Следи за файлами проекта в Solution Explorer'е. Один из *.h файлов закрался из Header files в Source files

- [x] Ноль..он и в Африке ноль. Нет смысла сравнивать с 0.0, если можно сравнить с 0

- [x] Для нахождения корня квадратного уравнения старший коэффициент не обязан быть положительным
```cpp
throw std::invalid_argument("first coefficient should be > 0");
```

- [x] Если один из операндов является double, то нет смысла писать в целых числах "окончания" .0
Вместо 4.0, можно писать просто 4
```cpp
const double d = b * b - 4.0 * a * c;
```

- [x] Квадратное уравнение не обязано не иметь комплексных корней. Лучше сообщить о том, что все корни исходного уравнения являются комплексными, т.е. не принадлежат множеству действительных чисел
```cpp
throw std::domain_error("Equation mustn't have complex roots");
```

- [x] Нет никакого смысла принимать double по константной ссылке. Принимай по значению
```cpp
EquationRoots2 Solve2(double const& a, double const& b, double const& c)
```

- [x] Полюби auto

- [x] Здесь явно делается что-то не так:
```cpp
#pragma warning(push)
#pragma warning(disable: 4715)
	double sgn(double const& x)
	{
		if (x > 0.0)   return 1.0;
		if (x == 0.0)  return 0.0;
		if (x < 0.0)   return -1.0;
	}
#pragma warning(pop)
```
Sign() можно у меня с репозитория забрать, там однострочник

- [x] Поехала кодировка. Переключись на UTF-8..или пиши на английском =)

- [x] Отлично будет выглядеть процесс оборачивания(см. мой репозиторий)
Например, Solve3() не решает кубические уравнения, она лишь вызывает Solve3ByViete(), попутно проверяя старший коэффициент и выполняя преобразование уравнение:
```cpp
/// ax^3 + bx^2 + cx + d = 0
/// Solve3() return sorted roots from low to high
SEquationRoot3 Solve3(double a, double b, double c, double d)
{
	if (a == 0)
	{
		throw std::invalid_argument("The equation of the third degree cannot have zero at the leading coefficient");
	}
	auto roots = Solve3ByViete(b / a, c / a, d / a);
	std::sort(roots.roots.begin(), roots.roots.end());
	return roots;
}
```

- [x] Заменить это:
```cpp
                if (q > 0)
		{
			// code
		}
		if (q < 0)
		{
			// code
		}
		if (q == 0)
		{
			// code
		}
```
на это:
```cpp
                if (q > 0)
		{
			// code
		}
		else if (q < 0)
		{
			// code
		}
		else
		{
			// code
		}
```

- [x] OpenCPPCoverage говорит, что код покрыт тестами на 4%(main() с return 0), что неудивительно, ведь весь управляющий код написан почему-то в h'нике
Так что тесты сейчас проверять не стану

**Comment by eligantRU** [comment]
- [x] Это точно не мой код, какой смысл принимать double по константной ссылке? По значению прими
```cpp
double sgn(double const& x)
{
	return (x > 0) - (x < 0);
}
```

- [x] sgn() здесь только для реализации и нужен. Убери его из *.h файла, для красоты можно в безымянный namespace спрятать (см. мой репозиторий)

**Comment by eligantRU** [comment]
- [x] Ты знаешь, что с этим делать:
```cpp
	if (d > 0.0)
```

**Comment by eligantRU** [comment]
- [x] Используй range-based for:
```cpp
			for (unsigned i = 0; i < roots.numRoots; i++)
			{
				std::cout << "x = " << roots.roots[i] << std::endl;
			}
```
```cpp
                        for (const auto root : roots.roots)
			{
				std::cout << "x = " << root << std::endl;
			}
```

**Comment by eligantRU** [comment]
- [x] Тесты недостаточны
![image](https://cloud.githubusercontent.com/assets/9452661/21472299/f5957e6e-cae3-11e6-8a1d-f669b30b1846.png)

![image](https://cloud.githubusercontent.com/assets/9452661/22100439/af3dcf82-de40-11e6-859e-6662f1febaec.png)

**Comment by alexey-malov** [comment]
![image](https://cloud.githubusercontent.com/assets/6040682/21953019/0a14d9ac-da3e-11e6-9052-f1c7b3ccd252.png)

- [x] ветка не покрыта тестами

**Comment by alexey-malov** [comment]
```
3 0 -2 0 -1
x = nan
x = nan
x = nan
x = nan
```

- [x] фанат группы "На-на"? Ожидаемый ответ: https://www.wolframalpha.com/input/?i=3x%5E4-2x%5E2-1%3D0

![image](https://cloud.githubusercontent.com/assets/6040682/21953069/001531da-da3f-11e6-8d64-80c5dbe3e39f.png)

**Comment by alexey-malov** [comment]
- [x] V591 The 'main' function does not return a value, which is equivalent to 'return 0'. It is possible that this is an unintended behavior.  6_lab_4 main.cpp 26

**Comment by alexey-malov** [comment]
![image](https://cloud.githubusercontent.com/assets/6040682/22172571/dd35a0a0-dfbb-11e6-9295-6535e899a1f4.png)

- [x] ветки тестами не покрыты
